### ISSUE TITLE
yajl.pc is not installed

### ISSUE THREAD

**Issue by vt-alt** [robohack/yajl#11] opened 2023-08-17 00:09 UTC
After successful build and `bmake install` - `yajl.pc` file does not appear in pkgconfig dir.

Version release-2.2

**Comment by robohack** [comment] 2023-09-26 23:45
I don't see this problem.   In my `make DESTDIR=dist install` output I find the following lines showing the installation of `yajl.pc` in the appropriate directory:

    #   install  /work/woods/f-yajl/dist/usr/lib/pkgconfig/yajl.pc
    install  -c  -r  -o woods  -g 1000  -m 444   yajl.pc /work/woods/f-yajl/dist/usr/lib/pkgconfig/yajl.pc

Can you provide more details, such as the version of make, the type of build (and target) system, the make command lines, etc.?  Thanks!

**Comment by robohack** [comment] 2024-04-07 21:16
Cannot reproduce, closing for now....

**Closed as completed by robohack** 2024-04-07 21:16 UTC
